print("Welcome to a short and simple adventure simulator. You remember mad-libs as a kid, right? Well, I'm going to ask you a couple of questions and then we're going to create an epic story together with you as the star!")
print()
environ = input("Type of place (i.e. fragile world, shining city, burning forest, etc.:")
agent = input("Type of subjective agent (i.e. curious humans, megalomaniacal squirrels, lustful zombies, etc.):")
saviors = input("A group of subjective agents (i.e. magical sculptors, humanoid kittens, sentient light waves/particles):")
needed_stuff = input("Stuff needed to accomplish something (i.e. mindbending courage, unending tenacity, rock-solid pliers, etc.):")
environ_saved = input("Type of place to be saved (i.e. a broken world, an aging chromosome, the relentless continuity of space-time):")
print()
print("In a", environ, "whose economy, politics, and culture are dominated by the influence of ", agent, ", a hardworking network of", saviors, "emerges through the revolutionary underground to save", environ_saved, ". They realized that only together did they have the", needed_stuff, "to overcome their", "\033[31m", "material conditions", "\033[0m", "in life!")